### ISSUE TITLE
QUERY: Organisation Membership

### ISSUE THREAD

**Issue by njsch** [latex-access/latex-access#11]
As a former and potential up-coming current contributor, I was wondering if one of @jakubl7545 or @lukaszgo1 might be happy to invite me to the organisation as a member? I do not need to be an owner, but being a collaborator more than a contributor would be nice, as I could then have the organisation pinned, not just to my profile readme but also to the organisations tab of my Github profile. Obviously, I am also happy to be explicitly denied direct push rights to the main repo without submitting PRs. I would be happy for either someone to do this for me, or if (at a stretch) someone made me an owner then I can do this myself.

I also wanted to confirm as an aside whether this is the proposed project that @lukaszgo1 emailed me about earlier this year? If so then I take it that this project has been forked by importing the original SourceForge SVN repo and not mine or Julien Cochuyt's fork, both of which have had their file indexes largely damaged by my unintentional line-blaming issues from 2 or 3 years ago? I have my Windows Git settings set to what should be the default of commiting Unix-style `\n` line-endings, so this should not happen any more.

**Comment by lukaszgo1** [comment]
> As a former and potential up-coming current contributor, I was wondering if one of @jakubl7545 or @lukaszgo1 might be happy to invite me to the organisation as a member? I do not need to be an owner, but being a collaborator more than a contributor would be nice, as I could then have the organisation pinned, not just to my profile readme but also to the organisations tab of my Github profile.

I've send you an invitation.

> Obviously, I am also happy to be explicitly denied direct push rights to the main repo without submitting PRs. I would be happy for either someone to do this for me, or if (at a stretch) someone made me an owner then I can do this myself.

The access rights to the main branch are set-up in a way which disallows even organization owner to push without submitting PR. The PR has also be approved by at least one reviewer.

> 
> I also wanted to confirm as an aside whether this is the proposed project that @lukaszgo1 emailed me about earlier this year? If so then I take it that this project has been forked by importing the original SourceForge SVN repo and not mine or Julien Cochuyt's fork, both of which have had their file indexes largely damaged by my unintentional line-blaming issues from 2 or 3 years ago? 

Yes this is the same project.

Since I believe you query has been answered I'm going to close this issue.

**Comment by njsch** [comment]
All good, thanks!
